import React from 'react';
import GenerationAnimation from '../src/GenerationAnimation';

export default {
  title: 'GenerationAnimation',
  component: GenerationAnimation,
  argTypes: {},
};

function Template(args) {
  return <GenerationAnimation {...args} />;
}

export const Basic = Template.bind({});
Basic.args = {
  rows: [
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Germany' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA/Argentina' },
    { Purpose: 'Technology Development', Country_of_Operator: 'Thailand' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    {
      Purpose: 'Navigation/Global Positioning',
      Country_of_Operator: 'USA/United Kingdom/Italy',
    },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Earth Science/Meteorology', Country_of_Operator: 'Norway' },
    { Purpose: 'Communications', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Meteorology', Country_of_Operator: 'USA' },
    { Purpose: 'Technology Development', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Vietnam' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Earth Observation', Country_of_Operator: 'Japan' },
    {
      Purpose: 'Communications/Technology Development',
      Country_of_Operator: 'Indonesia',
    },
    { Purpose: 'Communications', Country_of_Operator: 'United Arab Emirates' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Spain' },
    { Purpose: 'Communications', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Singapore' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'France' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Navigation/Global Positioning', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'UAE' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'India' },
    { Purpose: 'Communications', Country_of_Operator: 'Japan' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Turkey' },
    { Purpose: 'Astrophysics/Planetary Science', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Switzerland' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'Japan' },
    {
      Purpose: 'Earth Observation/Meteorology/Communications',
      Country_of_Operator: 'USA',
    },
    { Purpose: 'Communications', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Surveillance', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'Germany/USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Luxembourg' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications (experimental)', Country_of_Operator: 'India' },
    { Purpose: 'Communications', Country_of_Operator: 'Italy' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Communications', Country_of_Operator: 'Japan' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Vietnam' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    {
      Purpose: 'Remote Sensing/Technology Development',
      Country_of_Operator: 'France',
    },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications/Research', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Meteorology', Country_of_Operator: 'Netherlands' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'India/France' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Germany' },
    { Purpose: 'Communications', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Communications', Country_of_Operator: 'Japan' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Estonia' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'ESA/USA/Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Communications', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'Taiwan' },
    { Purpose: 'Communications', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Early Warning', Country_of_Operator: 'United Kingdom' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Scientific Research', Country_of_Operator: 'China (PR)' },
    { Purpose: 'Surveillance', Country_of_Operator: 'Russia' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Russia' },
    { Purpose: 'Technology Development', Country_of_Operator: 'Germany' },
    { Purpose: 'Communications', Country_of_Operator: 'Multinational' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Japan' },
    { Purpose: 'Solar Physics', Country_of_Operator: 'Brazil' },
    { Purpose: 'Remote Sensing/Reconnaissance', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'USA' },
    { Purpose: 'Communications', Country_of_Operator: 'Saudi Arabia' },
    { Purpose: 'Communications', Country_of_Operator: 'Algeria' },
  ],
};
